# Netlify configuration for Purrfect Stays

[build]
  command = "npm install && npm run build"
  publish = "dist"
  
# Processing and MIME type detection
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true
  
[build.processing.js]
  bundle = true
  minify = true

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_FLAGS = "--legacy-peer-deps"

# SPA routing configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self)"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' data: blob: https://*.google.com https://*.googletagmanager.com https://*.google-analytics.com https://*.gstatic.com https://*.doubleclick.net;
      script-src-elem 'self' 'unsafe-inline' data: blob: https://*.google.com https://*.googletagmanager.com https://*.google-analytics.com;
      style-src 'self' 'unsafe-inline' data: https://fonts.googleapis.com;
      font-src 'self' data: https://fonts.gstatic.com;
      img-src 'self' data: blob: https:;
      connect-src 'self' https://*.supabase.co https://*.google.com https://*.google-analytics.com https://*.doubleclick.net https://api.resend.com https://ipapi.co https://*.bigdatacloud.net https://api-bdc.io https://api.exchangerate-api.com;
      frame-ancestors 'none';
      object-src 'none';
      base-uri 'self';
      upgrade-insecure-requests;
    """

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JavaScript files - CRITICAL MIME type fix
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

# Module scripts specifically
[[headers]]
  for = "/*.mjs"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

# Ensure all built files are served with proper MIME types
[[headers]]
  for = "/*main*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optimize images
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment context specific settings
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"